# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: "Greet the world"
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  setup:
    desc: "Setup the project workspace"
    cmds:
      - task: install-db-cert
  install-db-cert:
    desc: "Install the CockroachDB certificate"
    cmds:
      - echo "Installing the CockroachDB certificate..."
      - |
        if [ -z "$COCKROACH_CLUSTER_ID" ]; then
          echo "Error: COCKROACH_CLUSTER_ID environment variable is not set"
          exit 1
        fi
        URL="https://cockroachlabs.cloud/clusters/$COCKROACH_CLUSTER_ID/cert"
        echo "URL=$URL"
        curl --create-dirs -o "$HOME/.postgresql/root.crt" "$URL"
  db-migrate:
    desc: "Run database migrations"
    cmds:
      - echo "Running db migrations..."
      - |
        if [ -z "$COCKROACH_DSN" ]; then
          echo "Error: COCKROACH_DSN environment variable is not set"
          exit 1
        fi
        migrate -database "${COCKROACH_DSN}" -path ./db/migrations up
