# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

env:
  COCKROACH_CLUSTER_ID: "{{.COCKROACH_CLUSTER_ID}}"

tasks:
  default:
    desc: "Greet the world"
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  setup:
    desc: "Setup the project workspace"
    cmds:
      - task: install-db-cert
  install-db-cert:
    desc: "Install the CockroachDB certificate"
    cmds:
      - echo "Installing the CockroachDB certificate..."
      - export URL="'https://cockroachlabs.cloud/clusters/${COCKROACH_CLUSTER_ID}/cert'"
      - echo "URL=${URL}"
      - curl --create-dirs -o "$HOME/.postgresql/root.crt" "${URL}"
  db-migrate:
    desc: "Run database migrations"
    cmds:
      - echo "Running db migrations..."
      # - COCKROACH_DSN="$(grep COCKROACH_DSN .env | cut -d '=' -f2- | tr -d '"')"
      - migrate -database "${COCKROACH_DSN}" -path ./db/migrations up
