# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: "Greet the world"
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  setup:
    desc: "Setup the project workspace"
    cmds:
      - task: install-db-cert
      - task: install-go-migrate
  install-db-cert:
    desc: "Install the CockroachDB certificate"
    cmds:
      - echo "Installing the CockroachDB certificate..."
      - |
        if [ -z "$COCKROACH_CLUSTER_ID" ]; then
          echo "Error: COCKROACH_CLUSTER_ID environment variable is not set"
          exit 1
        fi
        URL="https://cockroachlabs.cloud/clusters/$COCKROACH_CLUSTER_ID/cert"
        echo "URL=$URL"
        curl --create-dirs -o "$HOME/.postgresql/root.crt" "$URL"
  install-go-migrate:
    desc: "Install go-migrate"
    cmds:
      - echo "Installing go-migrate..."
      - go install -tags 'postgres,cockroachdb' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
  db-migrate:
    desc: "Run database migrations"
    cmds:
      - echo "Running db migrations..."
      - |
        if [ -z "$MIGRATIONS_DSN" ]; then
          # try getting from .env
          export "$(grep MIGRATIONS_DSN .env)"
          # error if its still not set
          if [ -z "$MIGRATIONS_DSN" ]; then
            echo "Error: MIGRATIONS_DSN environment variable is not set"
            exit 1
          fi
        fi
        migrate -database "${MIGRATIONS_DSN}" -path ./database/migrations up
  db-create-migration:
    desc: "Create a new database migration (usage: task db-create-migration -- migration_name)"
    cmds:
      - echo "Creating new migration..."
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Error: Migration name is required"
          echo "Usage: task db-create-migration -- migration_name"
          exit 1
        fi
        migrate create -ext sql -dir ./database/migrations {{.CLI_ARGS}}
